language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: X6QF7zle+i+uRKy4c1km2m6ZH2AmbFQqnqP4BGoI4CBB+6tRiQCGoz8wd8LkfBemJcaAaS5O/g9ltb/n+QLHG1sMo8pTy0p4YVGOz6Jp8W0JspSkd9J4gEflTqJ0N7ONXCfHbhb9Lq399OkNyR8lc9432bbLv35zc+0y3deIHFE=
  file:
    - "plain-text-data-to-json.js"
    - "plain-text-data-to-json.min.js"
  on:
    tags: true
